default:
    resource: "@DefaultBundle/Controller/"
    type:     annotation
    prefix:   /

hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login/redirect

facebook_login:
    pattern: /login/check/facebook
google_login:
    pattern: /login/check/google